version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:08"
      timezone: "America/New_York"
    allow: 
      - dependency-type: "all"
    target-branch: "staging"
      
    labels:
      - "security"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:08"
      timezone: "America/New_York"
    labels:
      - "security"
      - "actions"
