name: "Automerge For Dependabot"

on: pull_request_target

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{secrets.GH_TOKEN}}
          approve: true
          command: merge
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - auto-merge
    if: ${{ always() && github.actor == 'dependabot[bot]' }} # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_ALERTS }}
          description: 'Auto-merge ran for ${{ github.event.pull_request.title }} '
