name: "Automerge Dependabot"

on:
  pull_request:
    branches:
      - master

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
    uses: ridedott/merge-me-action@master
    with:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      MERGE_METHOD: MERGE