name: "Automerge Dependabot"

on:
  pull-request:
    branches:
      - master

jobs:
  merge-me:
    runs-on: ubuntu-latest
    steps:
      - name: "Merge me!"
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}