# .github/workflows/continuous-integration.yaml

jobs:
  merge-me:
    name: "Automerge Dependabot"
    runs-on: ubuntu-latest
    steps:
      - name: "Merge me!"
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}