name: "Dependabot-Discord Notification"
on: [pull_request]


jobs:
 notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    if: ${{ always() }} && startsWith(github.head.ref,'dependabot/npm_and_yarn/') == true # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          title: '${{ github.workflow }}: {{STATUS}}'
          description: '(DEV) Dependabot Package Pull Request ${{ github.event_name }} trigged this {{STATUS}}!'
          github-token: ${{ secrets.GH_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_ALERTS }}
        env:
          BRANCH_PREFIX: "dependabot/npm_and_yarn/"

