name: "Dependabot-Discord Notification"
on: 
  pull_request_target:
    branches:
      - staging
jobs:
  discord-notification:
    runs-on: ubuntu-latest
    name: From Dependabot
    if: github.actor == 'dependabot[bot]'
    steps:
    - uses: rjstone/discord-webhook-notify@v1.0.4
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        severity: info
        username: ${{ github.actor }}
        details: 'Pull Request branch name: ${{ github.event.pull_request.base.ref }} . This is the body ${{ github.event.pull_request.body }}'
        description: ' Dependabot Pull Request to ${{ github.event.pull_request.title }}'
        
          

