version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "9:00"
      timezone: "America/New_York"
    labels:
      - "security"
      - "npm"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "9:00"
      timezone: "America/New_York"
    labels:
      - "security"
      - "actions"
