name: "Dependabot-Discord Notification"
on: 
  pull_request:
    branches:
      - staging
jobs:
  discord-notification:
    runs-on: ubuntu-latest
    name: From Dependabot
    if: github.actor == 'dependabot[bot]'
    steps:
    - uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        description: ' Dependabot Pull Request ${{ github.event.pull_request.title }}'
        footer: ${{ github.event.pull_request.name }}.
        webhookUrl: ${{ secrets.DISCORD_ALERTS }}
          

