name: "ES Lint"

on: 
  push:
    branches-ignore: [production,'dependabot/npm_and_yarn/**']

jobs:
  es-lint:
    name: Lint javascript files
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.17.0']

    if: github.actor != 'dependabot[bot]'
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v2.2.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dev dependencies
      run: npm install

    - name: Running linter using eslint config file
      run: npx eslint -c ./.eslintrc.js .
      env:
        CI: true
        
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - es-lint
    if: ${{ failure() }} # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_ALERTS }}
