name: Deploy to Heroku

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.3]
    steps:
    - uses: actions/checkout@v1
    - name: Check for Updates
      run: npm update heroku 
    - name: Login
      uses: actions/heroku@master
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    - name: Push to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git push heroku master 
    - name: Run Seed
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}  
      run: heroku run npm run seed -a ${{ secrets.HEROKU_APP_NAME }}
    - name: Boot API
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku run npm run sstart -a ${{ secrets.HEROKU_API_KEY }}
