name: "Postman Test Runner"
on:
  push:
    branches:
      - staging
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matt-ball/newman-action@master
        with: # This is being done via the API
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ POSTMAN_COLLECTION_ID }}
          environment: ${{ POSTMAN_ENVIRONMENT }}
  
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - test-api
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_ALERTS }}
   
