name: "Postman Test Runner"
on:
  push:
    branches:
      - staging
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Run Newman
        uses: anthonyvscode/newman-action@v1
        id: run-api-tests
        with: # This is being done via the API
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
          environment: ${{ secrets.POSTMAN_ENVIRONMENT }}
          reporters: cli
      
      - name: Export Summary from Outputs
        run: echo ${{ steps.run-api-tests.outputs.summary_full }}
  
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - test-api
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_ALERTS }}
   
