name: "Deploy to Heroku Production"

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14.17.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_STAGING}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
