name: "Deploy to Heroku Staging"

on:
  push:
    branches:
      - staging

jobs:

  es-lint:
    name: Lint javascript files
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.15.0']

    if: github.actor != 'dependabot[bot]'
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dev dependencies
      run: npm install

    - name: Running linter using eslint config file
      run: npx eslint -c ./.eslintrc.js .
      env:
        CI: true

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14.17.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}